/**
 * @description 动画 attributes 属性 utils
 * @author FluffyChi-Xing
 */




/**
 * @description 动画类型映射列表
 * @author FluffyChi-Xing
 */
export const animationList: RenrenInterface.IAnimation[] = [
  {
    label: '进入',
    children: [
      { key: '渐显', value: 'fadeIn' },
      { key: '向右进入', value: 'fadeInLeft' },
      { key: '向左进入', value: 'fadeInRight' },
      { key: '向上进入', value: 'fadeInUp' },
      { key: '向下进入', value: 'fadeInDown' },
      { key: '向右长距进入', value: 'fadeInLeftBig' },
      { key: '向左长距进入', value: 'fadeInRightBig' },
      { key: '向上长距进入', value: 'fadeInUpBig' },
      { key: '向下长距进入', value: 'fadeInDownBig' },
      { key: '旋转进入', value: 'rotateIn' },
      { key: '左顺时针旋转', value: 'rotateInDownLeft' },
      { key: '右逆时针旋转', value: 'rotateInDownRight' },
      { key: '左逆时针旋转', value: 'rotateInUpLeft' },
      { key: '右逆时针旋转', value: 'rotateInUpRight' },
      { key: '弹入', value: 'bounceIn' },
      { key: '向右弹入', value: 'bounceInLeft' },
      { key: '向左弹入', value: 'bounceInRight' },
      { key: '向上弹入', value: 'bounceInUp' },
      { key: '向下弹入', value: 'bounceInDown' },
      { key: '光速从右进入', value: 'lightSpeedIn' },
      { key: '光速从右退出', value: 'lightSpeedOut' },
      { key: '中心X轴旋转', value: 'flipInX' },
      { key: '中心Y轴旋转', value: 'flipInY' },
      { key: '左长半径旋转', value: 'rollIn' },
      { key: '由小变大进入', value: 'zoomIn' },
      { key: '左变大进入', value: 'zoomInLeft' },
      { key: '右变大进入', value: 'zoomInRight' },
      { key: '向上变大进入', value: 'zoomInUp' },
      { key: '向下变大进入', value: 'zoomInDown' },
      { key: '向右滑动展开', value: 'slideInLeft' },
      { key: '向左滑动展开', value: 'slideInRight' },
      { key: '向上滑动展开', value: 'slideInUp' },
      { key: '向下滑动展开', value: 'slideInDown' },
    ],
  },
  {
    label: '强调',
    children: [
      { key: '弹跳', value: 'bounce' },
      { key: '闪烁', value: 'flash' },
      { key: '放大缩小', value: 'pulse' },
      { key: '放大缩小弹簧', value: 'rubberBand' },
      { key: '左右晃动', value: 'headShake' },
      { key: '左右扇形摇摆', value: 'swing' },
      { key: '放大晃动缩小', value: 'tada' },
      { key: '扇形摇摆', value: 'wobble' },
      { key: '左右上下晃动', value: 'jello' },
      { key: 'Y轴旋转', value: 'flip' },
    ],
  },
  {
    label: '退出',
    children: [
      { key: '渐隐', value: 'fadeOut' },
      { key: '向左退出', value: 'fadeOutLeft' },
      { key: '向右退出', value: 'fadeOutRight' },
      { key: '向上退出', value: 'fadeOutUp' },
      { key: '向下退出', value: 'fadeOutDown' },
      { key: '向左长距退出', value: 'fadeOutLeftBig' },
      { key: '向右长距退出', value: 'fadeOutRightBig' },
      { key: '向上长距退出', value: 'fadeOutUpBig' },
      { key: '向下长距退出', value: 'fadeOutDownBig' },
      { key: '旋转退出', value: 'rotateOut' },
      { key: '左顺时针旋转', value: 'rotateOutDownLeft' },
      { key: '右逆时针旋转', value: 'rotateOutDownRight' },
      { key: '左逆时针旋转', value: 'rotateOutUpLeft' },
      { key: '右逆时针旋转', value: 'rotateOutUpRight' },
      { key: '弹出', value: 'bounceOut' },
      { key: '向左弹出', value: 'bounceOutLeft' },
      { key: '向右弹出', value: 'bounceOutRight' },
      { key: '向上弹出', value: 'bounceOutUp' },
      { key: '向下弹出', value: 'bounceOutDown' },
      { key: '中心X轴旋转', value: 'flipOutX' },
      { key: '中心Y轴旋转', value: 'flipOutY' },
      { key: '左长半径旋转', value: 'rollOut' },
      { key: '由小变大退出', value: 'zoomOut' },
      { key: '左变大退出', value: 'zoomOutLeft' },
      { key: '右变大退出', value: 'zoomOutRight' },
      { key: '向上变大退出', value: 'zoomOutUp' },
      { key: '向下变大退出', value: 'zoomOutDown' },
      { key: '向左滑动收起', value: 'slideOutLeft' },
      { key: '向右滑动收起', value: 'slideOutRight' },
      { key: '向上滑动收起', value: 'slideOutUp' },
      { key: '向下滑动收起', value: 'slideOutDown' },
    ],
  },
];


/**
 * @description 动画名称类名映射表
 */
export const animationNameValueMap: Map<string, string> = new Map<string, string>([
  ['渐显', 'fadeIn' ],
  ['向右进入', 'fadeInLeft'],
  ['向左进入', 'fadeInRight'],
  ['向上进入', 'fadeInUp'],
  ['向下进入', 'fadeInDown'],
  ['向右长距进入', 'fadeInLeftBig'],
  ['向左长距进入', 'fadeInRightBig'],
  ['向上长距进入', 'fadeInUpBig'],
  ['向下长距进入', 'fadeInDownBig'],
  ['旋转进入', 'rotateIn'],
  ['左顺时针旋转', 'rotateInDownLeft'],
  ['右逆时针旋转', 'rotateInDownRight'],
  ['左逆时针旋转', 'rotateInUpLeft'],
  ['右逆时针旋转', 'rotateInUpRight'],
  ['弹入', 'bounceIn'],
  ['向右弹入', 'bounceInLeft'],
  ['向左弹入', 'bounceInRight'],
  ['向上弹入', 'bounceInUp'],
  ['向下弹入', 'bounceInDown'],
  ['光速从右进入', 'lightSpeedIn'],
  ['光速从右退出', 'lightSpeedOut'],
  ['中心X轴旋转', 'flipInX'],
  ['中心Y轴旋转', 'flipInY'],
  ['左长半径旋转', 'rollIn'],
  ['由小变大进入', 'zoomIn'],
  ['左变大进入', 'zoomInLeft'],
  ['右变大进入', 'zoomInRight'],
  ['向上变大进入', 'zoomInUp'],
  ['向下变大进入', 'zoomInDown'],
  ['向右滑动展开', 'slideInLeft'],
  ['向左滑动展开', 'slideInRight'],
  ['向上滑动展开', 'slideInUp'],
  ['向下滑动展开', 'slideInDown'],
  ['弹跳', 'bounce'],
  ['闪烁', 'flash'],
  ['放大缩小', 'pulse'],
  ['放大缩小弹簧', 'rubberBand'],
  ['左右晃动', 'headShake'],
  ['左右扇形摇摆', 'swing'],
  ['放大晃动缩小', 'tada'],
  ['扇形摇摆', 'wobble'],
  ['左右上下晃动', 'jello'],
  ['Y轴旋转', 'flip'],
  ['渐隐', 'fadeOut'],
  ['向左退出', 'fadeOutLeft'],
  ['向右退出', 'fadeOutRight'],
  ['向上退出', 'fadeOutUp'],
  ['向下退出', 'fadeOutDown'],
  ['向左长距退出', 'fadeOutLeftBig'],
  ['向右长距退出', 'fadeOutRightBig'],
  ['向上长距退出', 'fadeOutUpBig'],
  ['向下长距退出', 'fadeOutDownBig'],
  ['旋转退出', 'rotateOut'],
  ['左顺时针旋转', 'rotateOutDownLeft'],
  ['右逆时针旋转', 'rotateOutDownRight'],
  ['左逆时针旋转', 'rotateOutUpLeft'],
  ['右逆时针旋转', 'rotateOutUpRight'],
  ['弹出', 'bounceOut'],
  ['向左弹出', 'bounceOutLeft'],
  ['向右弹出', 'bounceOutRight'],
  ['向上弹出', 'bounceOutUp'],
  ['向下弹出', 'bounceOutDown'],
  ['中心X轴旋转', 'flipOutX'],
  ['中心Y轴旋转', 'flipOutY'],
  ['左长半径旋转', 'rollOut'],
  ['由小变大退出', 'zoomOut'],
  ['左变大退出', 'zoomOutLeft'],
  ['右变大退出', 'zoomOutRight'],
  ['向上变大退出', 'zoomOutUp'],
  ['向下变大退出', 'zoomOutDown'],
  ['向左滑动收起', 'slideOutLeft'],
  ['向右滑动收起', 'slideOutRight'],
  ['向上滑动收起', 'slideOutUp'],
  ['向下滑动收起', 'slideOutDown'],
]);
