/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    BaseMaterial: typeof import('./src/components/material/BaseMaterial.vue')['default']
    Context: typeof import('./src/components/Context.vue')['default']
    DisplayItem: typeof import('./src/components/DisplayItem.vue')['default']
    Draggable: typeof import('./src/components/Draggable.vue')['default']
    DrawerTransition: typeof import('./src/components/DrawerTransition.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDrawerTransition: typeof import('element-plus/es')['ElDrawerTransition']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    HighLightLang: typeof import('./src/components/HighLightLang.vue')['default']
    MaterialItem: typeof import('./src/components/MaterialItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectArea: typeof import('./src/components/SelectArea.vue')['default']
    Shape: typeof import('./src/components/Shape.vue')['default']
    TestItem: typeof import('./src/components/TestItem.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
